# Generated by Django 3.1.7 on 2023-11-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carBidderApp', '0002_auto_20231113_2202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
